aggregator:
  ip: 213.52.128.114
  port: 5000
connection:
  info:
    id: party0
    ip: 192.168.0.4
    port: 5000
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: true
data:
  info:
    batch_size: 64
    data_set: CIFAR10/random/data_party0.npz
  name: Cifar10KerasDataGenerator
  path: DataHandlers/DataGenerators.py
local_training:
  name: LocalTrainingHandler
  path: ibmfl.party.training.local_training_handler
model:
  name: KerasFLModel
  path: ibmfl.model.keras_fl_model
  spec:
    model_definition: Models/keras_classifier_cifar10/compiled_keras.h5
    model_name: keras-cnn
protocol_handler:
  name: PartyProtocolHandler
  path: ibmfl.party.party_protocol_handler
